url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Sheffield Ethical Student Hackers" # the name of your site, e.g. ACME Corp.

collections:
  committee:
    output: true
  committee_old:
    output: true
  other-opps:
    output: true
  priv-sector:
    output: true
  pub-sector:
    output: true
  ind-partners:
    output: true
  resources:
    output: true
  session-slides:
    output: true
  worksheets:
    output: true
  soc-partners:
    output: true
  sponsors:
    output: true
  sessions:
    output: true
  wiki:
    output: true
